### ISSUE TITLE
urlTitle Structure Field

### ISSUE THREAD

**Issue by brentgriffin** [bgriffin-zenhub/core#32]
<a href="https://github.com/thequicksilver"><img src="https://avatars.githubusercontent.com/u/784502?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thequicksilver](https://github.com/thequicksilver)**
_Thursday May 03, 2012 at 18:12 GMT_
_Originally opened as https://github.com/dotCMS/core/issues/266_

---

Feature Request: Rather than the constant use of custom fields to create slugs for URLs on structured content, since it's such a common and standard use feature of structured content, it might be worth making that into a standard field type. Add it to a structure, and then define its source field and it will generate the slug for you (ideally allowing you to edit it afterwards - think the way Wordpress does it).

**Comment by brentgriffin** [comment]
<a href="https://github.com/joelgoodman"><img src="https://avatars.githubusercontent.com/u/1237185?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joelgoodman](https://github.com/joelgoodman)**
_Thursday May 03, 2012 at 19:29 GMT_

---

+1 Consistency is a huge issue without a standardized field.

**Comment by wezell** [comment]
Don't disagree.  Hopefully we can get there with custom fields
